name: Build Android App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-python: '3.10'

    - name: Install Build Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev tk-dev libgdbm-compat-dev libreoffice-dev libmpdec-dev
        pip3 install --user --upgrade buildozer cython virtualenv

    - name: Initialize Buildozer Config
      run: |
        ~/.local/bin/buildozer init
        # Ajusta as configurações para compilar o index.html diretamente como um WebApp nativo
        sed -i 's/# title = My Application/title = BaseConvert/g' buildozer.spec
        sed -i 's/# package.name = myapp/package.name = baseconvert/g' buildozer.spec
        sed -i 's/# package.domain = org.test/package.domain = com.brayan/g' buildozer.spec
        sed -i 's/source.include_exts = py,png,jpg,kv,atlas/source.include_exts = html,css,js,png,jpg/g' buildozer.spec
        sed -i 's/# requirements = sqlite3,kivy/requirements = python3,kivy,android/g' buildozer.spec
        sed -i 's/# android.archs = arm64-v8a, armeabi-v7a/android.archs = arm64-v8a/g' buildozer.spec
        sed -i 's/# android.accept_sdk_license = False/android.accept_sdk_license = True/g' buildozer.spec

    - name: Build Android APK
      run: |
        # Executa a compilação do APK em modo debug
        ~/.local/bin/buildozer android debug

    - name: Upload Finished APK
      uses: actions/upload-artifact@v4
      with:
        name: meu-aplicativo-apk
        path: .blur/bin/*.apk